import { Sidebar } from '@/components/sidebar'
import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} grid grid-cols-[16rem_1fr] grid-rows-[auto_1fr] h-screen`}
      >
        <Header />
        <Sidebar />
        <div className="flex-1 px-12 py-8 overflow-y-scroll">{children}</div>
      </body>
    </html>
  )
}
